feat: add strapi annuaire page
SocialGouv/mda pull request #132
Opened 2023-02-23 18:07 UTC by sutter

2023-03-01 14:34 UTC, paulsouche requested changes

2023-03-01 14:34 UTC, paulsouche commented on apps/strapi/src/bootstrap/dev/seed-db.ts
> +  "api::accueil.accueil": import("../../utils/seed/home.json"),
Peut être renommer en accueil.json ?

2023-03-01 14:34 UTC, paulsouche commented on apps/web/src/components/base/client/BreadcrumbDynamic.tsx
> +      } else {
Pas besoin de else :see_no_evil:

2023-03-01 14:34 UTC, paulsouche commented on apps/strapi/config/sync/user-role.public.json
> -    },
Juste pour être sur (je n'ai pas encore le background nécessaire pour en juger) mais tu supprimes l'accès aux aides ?

2023-03-02 09:46 UTC, sutter commented on apps/strapi/config/sync/user-role.public.json
> -    },
Non c'est une connerie de ma part.

2023-03-02 09:48 UTC, sutter commented on apps/web/src/components/base/client/BreadcrumbDynamic.tsx
> +      } else {
Sans ce else je me retrouve avec un trou dans mon breadcrumb

2023-03-02 13:05 UTC, paulsouche approved these changes

2023-03-02 13:06 UTC, sutter commented on apps/web/src/components/base/client/BreadcrumbDynamic.tsx
> +      } else {
Ha ok je n'avais pas compris. Oui c'est vrai que le else est implicite.

2023-03-02 14:56 UTC, merged