240 message dalerte lors de la saisie de lurl dans un navigateur
SocialGouv/mda pull request #242
Opened 2023-04-06 08:52 UTC by igorrenquin

Ajout d'un redirect de l'url www.maisondelautisme.gouv.fr vers maisondelautisme.gouv.fr

Closes #x

# Objectif(s)

2023-04-06 08:54 UTC, revolunet approved these changes

2023-04-07 07:04 UTC, revolunet approved these changes

2023-04-07 07:12 UTC, revolunet requested changes
pas sur que ca marche comme cela a cause du gouv.fr

2023-04-07 18:45 UTC, paulsouche commented
> pas sur que ca marche comme cela a cause du gouv.Fr

Je ne vois pas de F majuscule ? Est ce que je comprends bien ?

2023-04-11 07:52 UTC, revolunet commented
Est-ce que [www.maisondelautisme.gouv.fr](http://www.maisondelautisme.gouv.fr/) doit utiliser un certificat spécifique ? 

Si oui il ne faut pas l'inclure ici mais créer un ingress dédié qui point vers le bon secret/certificat [comme ici](https://github.com/SocialGouv/egapro/blob/master/.kontinuous/env/prod/templates/redirect-index-egapro.ingress.yaml)

2023-04-17 14:00 UTC, merged